# Generated by Django 5.2.6 on 2025-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('organizer', 'Organizer'), ('attendee', 'Attendee')], default='attendee', max_length=15, null=True),
        ),
    ]
